apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: {{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}} 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}} 
    spec:
      containers:
        - name: {{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}} 
          image: {{ containerRegistryConnection.Authorization.Parameters.loginServer }}/{{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}}
          ports:
          - containerPort: {{ servicePort }}
---
apiVersion: v1
kind: Service
metadata:
    name: {{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}}
spec:
    type: LoadBalancer
    ports:
    - port: {{ servicePort }} 
    selector:
        app: {{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}}
